### ISSUE TITLE
Need an abstract class for GameObjects

### ISSUE THREAD

**Issue by benji-rea** [Timothy-Needs-to-Die/TimothE#2]
Ryan highlighted a need for abstract class for GameObjects 

@AdamHarris-GamesProgrammer please advise

**Comment by benji-rea** [comment]
@JackDobie to create this abstract once finished up on UI work.

Reason being to force users to enter the parameters for the GameObject whenever a new GameObject is created and to remove the need for a virtual void so update can be overwritten

**Comment by JackDobie** [comment]
Made the Start, Update, and Exit functions virtual so they can be overwritten by a new class.
