### ISSUE TITLE
Diagnonal Movement doesn't appear to be calculated correctly

### ISSUE THREAD

**Issue by benji-rea** [Timothy-Needs-to-Die/TimothE#6]
The player is able to accelerate rapidly if they strafe along a diagonal path as opposed to straight liner travel as shown in the attached sketch
![image](https://user-images.githubusercontent.com/57398964/168605869-9e972537-c055-4267-9ffb-917d78860a5d.png)

**Comment by JackDobie** [comment]
Fixed by normalising the movement vector when magnitude exceeds 1
